arb-dir: lib/l10n
format: true
output-class: AppL10n
output-dir: lib/l10n/gen
output-localization-file: app_localizations.dart
template-arb-file: app_en.arb
nullable-getter: false
untranslated-messages-file: lib/l10n/gen/app_localizations_untranslated.json